name: Deploy to EC2 machine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Git-build:
    name: Build Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4

  ssh-ec2-install-nginx:
    name: Prepare EC2 Stage
    runs-on: ubuntu-latest
    needs: Git-build

    steps:
      - name: SSH into EC2 and Prepare Target Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSHKEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install nginx -y
            sudo chown -R ${{ secrets.EC2_USERNAME }} /var/www/html/
            sudo chmod -R 755 /var/www/html/

  deploy-to-ec2:
    name: Deploy to EC2 Stage
    runs-on: ubuntu-latest
    needs: ssh-ec2-install-nginx

    steps:
      - name: Copy code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSHKEY }}
          port: 22
          source: ./index.html
          target: /var/www/html/

  restart-nginx:
    name: Restart Nginx Stage
    runs-on: ubuntu-latest
    needs: deploy-to-ec2

    steps:
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOSTNAME }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSHKEY }}
          port: 22
          script: |
            sudo systemctl restart nginx
